### ISSUE TITLE
コンセプト・開発方針

### ISSUE THREAD

**Issue by shimoju** [pepabo-mobile-app-training/turmeric#1]
## コンセプト
- リストを活用したい人向けの、「リスト指向Twitterアプリ」
- リストを一瞬で行き来でき、リストメンバーの管理がしやすいUIを目指す
## ターゲットイメージ
- 書くより読むほうが多い人
- リストをよく使う/使っていきたい人
  - リストを使おうとしたけど使いやすいアプリがなくあまり活用できていない人（俺たち）が、リストを使いこなせるようにしたい
- [ある人が実施したTwitterアプリ投票](http://hitoriblog.com/?p=39845)によると、公式以外のアプリを使う動機としてリスト機能をあげる人は多かった
  - 割と需要はありそう
## Prott

https://prottapp.com/app/#/projects/57cd3dec4942fb54c6781b1c

**Comment by shimoju** [comment]
## Rails APIの方のあれ
- APIのみでWebのUIは作成しない
- リストに関わる機能を追加する
  - リストの作成、メンバーの追加・編集(フォロー/フォロワーの実装を参考に、かな)
  - まずざっくりとAPI(リクエスト・レスポンスJSON)の仕様を考える→静的なJSONを作ってそれをもとにアプリ側の機能を実装→APIが完成したら差し替える
  - のような手法にしないと効率が悪そう

## モバイルアプリ
- 今回一番フォーカスしたい部分はリストの部分なので、既にRails APIにある機能をすべてモバイルでできるようにすることはこだわらない
- ただし最低限のタイムライン、プロフィールやフォロー/フォロワーがないとリストの使いやすさもわからないので、まずはここからということになりそう

**Comment by ry023** [comment]
# XCode開発時のルール

逐次追加予定
- **1画面, 1StoryBoard**
  - 今回の開発は3人の複数人開発となるため、並行して複数の画面を開発することとなる
  - StoryBoardを複数画面で共通化してしまうと、Conflictが生じた際の修正にかける労力が大きい
  - 画面ごとにStoryBoardを独立させ、上記問題を避ける
- **Trelloによるタスク管理**
  - (開発全体で言えることだが) 作業前にTodoを出しておき、それを消化する形で開発を進める
  - 作業開始時はDoingにタスクを移動し、自分が担当に割り振られていることを確認。終わったらDoneへ
  - 作業のカテゴリに応じてラベル付け
